Force using importlib_resources in Python < 3.9
Force using the external importlib_resources package based on Python
version rather than the presence of the built-in importlib.resources.
The latter does not have the needed files() method in Python < 3.9,
and therefore results in test failures:

  E       AttributeError: module 'importlib.resources' has no attribute 'files'

This affects specifically Python 3.7 and 3.8 that have an older version
of importlib.resources module.